# Generated by Django 4.1 on 2022-08-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
